name: english_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  english_words: ^4.0.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.2.0
  like_button: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  #
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/
    - assets/fonts/
    - assets/fonts/sen/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/sen/Sen-Regular.ttf
        - asset: assets/fonts/sen/Sen-Bold.ttf
          weight: 700
